def raise_exception():
    raise TypeError("exception has been raised")
print("exception has been raised")

# Example usage:
raise_exception()


