def raise_exception():
    raise TypeError("exception has been raised")

# Example usage:
raise_exception("exception has been raised")


